package com.icbt.pahanaeduonlinebillingsystem.common.exception;

/**
 * @author Thisara Kavishka
 * @date 2025-07-22
 * @since 1.0
 */
public enum ExceptionType {

    // ===== CUSTOMER EXCEPTION TYPES =====
    CUSTOMER_NOT_FOUND,
    CUSTOMER_ALREADY_EXISTS,
    INVALID_CUSTOMER_INPUTS,
    CUSTOMER_ACCOUNT_NUMBER_ALREADY_EXISTS,
    CUSTOMER_PHONE_NUMBER_ALREADY_EXISTS,
    CUSTOMER_CREATION_FAILED,
    CUSTOMER_UPDATE_FAILED,
    CUSTOMER_DELETION_FAILED,

    // ===== USER EXCEPTIONS TYPES=====
    USER_NOT_FOUND,
    USER_ALREADY_EXISTS,
    INVALID_CREDENTIALS,
    PASSWORD_HASHING_FAILED,
    USER_CREATION_FAILED,
    USER_UPDATE_FAILED,
    USER_DELETION_FAILED,
    UNAUTHORIZED_ACCESS,

    // ===== ITEM EXCEPTIONS =====
    ITEM_NOT_FOUND,
    ITEM_ALREADY_EXISTS, // Based on name uniqueness
    INVALID_ITEM_INPUTS,
    ITEM_CREATION_FAILED,
    ITEM_UPDATE_FAILED,
    ITEM_DELETION_FAILED,
    INSUFFICIENT_STOCK,

    CONFIGURATION_ERROR,
    DATABASE_ERROR,
    INTERNAL_SERVER_ERROR,
}
